### ISSUE TITLE
Autolaunch does not work with User tasks

### ISSUE THREAD

**Issue by ScottA38** [philfontaine/autolaunch#16]
This extension works fine with per-project tasks, but when I add `auto: true` to user tasks.json I am not getting any action on editor open.

I saw that [runon](https://code.visualstudio.com/docs/editor/tasks#_run-behavior) was referenced as a native replacement for this plugin, but it is on folder open only which I don't understand how it is a replacement for opening the editor, also this would not global as desired. Maybe I am missing something?

I know this is not maintained any more, but maybe there is a simple PR for this?

As an example, here is a task I want to _try_ and run on all projects (even though it is a task for Ruby projects only, hence `bash -lc` arguments for 'command not found' safety.) I put it in user config with `runon: folderOpen`, but it doesn't seem to work for global scope (even though intellisense says it is valid config)

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "promptOnClose": true,
    "tasks": [
        {
            "label": "Generate ruby ripper tags (bustagem)",
            "type": "shell",
            "command": "bundle",
            "options": {
                "shell": {
                    "args": ["-c", "-l"]
                }
            },
            "args": [
                "exec",
                "ripper-tags",
                "-f",
                "TAGS",
                "-R",
                "--force",
                "--extra=q"
            ],
            "runOptions": {
                "runOn": "folderOpen"
            }
        }
    ]
}
```

**Comment by philfontaine** [comment]
Added in 2.1.1
