### ISSUE TITLE
Workspace with more folders - auto run not working

### ISSUE THREAD

**Issue by lukaszpolowczyk** [philfontaine/autolaunch#3]
1. Open folder project
2. File > Add Folder to Workspace...
The auto launcher for tasks has stopped working since then.

Something similar happened before the update.
At that time, it was necessary to add the setting of the auto start to the global settings, because when they were in the folder or workspace settings it did not work.

Now, with the `"auto": true` parameter in the tasks.json file, I've only got one folder. For workspace with many folders does not work.

**Comment by philfontaine** [comment]
Just published 1.1.0 which adds Workspace support. Thank you for your feedback!
