### ISSUE TITLE
Task with the same label in another folder is wrongly selected

### ISSUE THREAD

**Issue by jingyu9575** [philfontaine/autolaunch#4]
1. Open a workspace with 2 folders, A and B.
2. In both folders, create tasks with the same label e.g. "Watch".
3. Set `"auto": true` in the "Watch" task of folder B.
4. Reload VS Code.

Actual Result: The "Watch" task of folder A is started.
Expected: The "Watch" task of folder B is started.

**Comment by philfontaine** [comment]
This issue cannot be resolved simply.

Have a look at this snippet from [vs code documentation](https://code.visualstudio.com/Docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks):
```json
{
    "key": "ctrl+h",
    "command": "workbench.action.tasks.runTask",
    "args": "Run tests"
}
```
This is basically what this extension does. You can test this behaviour, but vscode simply loops over the workspace folders until it finds a matching label.

I think the only thing we can do is avoid name collision. I will add it to the readme.
