### ISSUE TITLE
Update to the new vscode task API

### ISSUE THREAD

**Issue by philfontaine** [philfontaine/autolaunch#5]

**Comment by philfontaine** [comment]
Problems:

- The new API has no support for custom fields (like auto: true) 
  - Solution: See last comment
- The fetchTasks method is really slow because it fetches all possibles tasks
  - Edit: It seems slow, but the actual time to launch a task is exactly the same

**Comment by haugerbr** [comment]
I'm assuming this is why it's telling me that the property is not allowed in tasks.json but still works correctly in functionality.

**Comment by philfontaine** [comment]
Not exactly.

The warning is due to the fact that vscode does not know what the property `auto` is, so it simply warns the user. This is documented [here](https://github.com/philfontaine/autolaunch#known-issues). It is not really problematic because the extension still finds the `auto` property in the object, and works as expected.

However, with the new API, the property `auto` is simply filtered out of the object, so the extension cannot work properly. 

Because of that (plus the fact that the new API is terribly slow), I won't update to the new API until the old one becomes unsupported.

**Comment by philfontaine** [comment]
Upcoming solution:

- Use the current procedure to get task definitions
- use fetchTasks to get all possible tasks
- Make sure to have a perfect 1:1 mapping of the definitions with the actual tasks
  - Name should match
  - Workspace should match
  - Name collisions within the same workspace will probably not be supported
