### ISSUE TITLE
Add a command to re-launch tasks

### ISSUE THREAD

**Issue by NoriSte** [philfontaine/autolaunch#8]
Most of the times I've 2-4 tasks launched automatically and then I add one more terminal window to launch some additional tasks manually. Often I made a mistake and I stop a task launched automatically by the extension. What's the easiest solution for me? Closing the whole project and reopening it so all the tasks will be re-launched.
That's because you extension allows me to completely forgot which tasks I set to be launched automatically and if I stop a task... I should open the `task.json` file and look at which one I stopped (I can't go up with the arrow key in the task window to relaunch it because VSCode tells me that the window will be reused and so it isn't interactive).

What do you think?

**Comment by philfontaine** [comment]
What you describe is just normal vscode behaviour, this extension does nothing more than doing:
- View -> Command Palette -> Tasks: Run tasks -> Select the task.

If you accidentally stop a task, you still have the name of the task in the terminal. It won't close until you press a key, like said in the message. So you can grab the name and rerun it manually using the procedure I described above.

![image](https://user-images.githubusercontent.com/16233697/43360047-6f754f50-927c-11e8-91e0-f11abc50373f.png)

**Comment by NoriSte** [comment]
Hi
You're right but consider that if I accidentally stop a task it's because probably I haven't realized that the focus was on the terminal window... so I use a shortcut to launch a command (that probably I expect to launch in the editor window), I stop a task (but I'm focused on the editor window so probably I completely miss out that I stopped a task), I re-use the shortcut again (because I'm focused on the editor window and I haven't received any feedback from my previous shortcut) but doing so I close the task window (because in the meanwhile it's telling me "Terminal will be reused... press any key to close it") and then finally I realise I was focusing on the wrong window.

In the end: if I stop a task 99% of the times I'll incidentally close the terminal window of the task ;-)
If you change your mind and you want to implement it let me know that I already have a PR ready (I tested it with the old version but I take no time to port it on the new version), if you think it's a useless feature or a feature useful just for my special case... thanks anyway and see you at the next issue I'll raise :-)

**Comment by NoriSte** [comment]
I found another scenario where a dedicated command could be useful: while setting up the auto-tasks of a project or when I've installed the extension for the first time and I'm literally playing with the tasks.json file... the only way to test the extension is to close the workspace and reopen it to see the extension in action...

**Comment by philfontaine** [comment]
How do you handle already running tasks? You need to terminate them, right?

It it possible to terminate a task but it is not possible to terminate a launch configuration.

**Comment by NoriSte** [comment]
I'll take a look at those ones, thank you 👍
